import { Inter } from "next/font/google";
import MyProfilePic from "./components/MyProfilePic";
import NavBar from "./components/NavBar";
import NavBar2 from "./components/NavBar2";
import "./globals.css";

const inter = Inter({ subsets: ["latin"], preload: true });

export const metadata = {
  title: "Hector Lopez Starter",
  description: "Generated by hector Lopez",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} dark:bg-slate-800`}>
        <nav>
          <h1>my navbar</h1>
        </nav>
        <NavBar />
        <NavBar2 />
        <MyProfilePic />
        {children}
      </body>
    </html>
  );
}
