import { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "./(components)/NavBar";
import NavBar2 from "./(components)/NavBar2";
import "./globals.css";

const inter = Inter({ subsets: ["latin"], preload: true });

export const metadata: Metadata = {
  title: "Hector Lopez Starter",
  description: "Generated by hector Lopez",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} dark:bg-slate-800`}>
        <nav>
          <h1>my navbar</h1>
        </nav>
        <NavBar />
        <NavBar2 />
        <main
          className="px-4 md:px-6 prose prose-xl
        åprose-slate dark:prose-invert mx-auto"
        >
          {children}
        </main>
      </body>
    </html>
  );
}
